version: 2

jobs:
  python-3.7-client-5:
    docker:
      - image: python:3.7
      - image: redis:5.0
    steps:
      - checkout
      - run: python -m pip install -r test_requirements.txt
      - run: pytest tests/client/

  python-3.7-client-6:
    docker:
      - image: python:3.7
      - image: redis:6.2
    steps:
      - checkout
      - run: python -m pip install -r test_requirements.txt
      - run: pytest tests/client/

  python-3.8-client-5:
    docker:
      - image: python:3.8
      - image: redis:5.0
    steps:
      - checkout
      - run: python -m pip install -r test_requirements.txt
      - run: pytest tests/client/

  python-3.8-client-6:
    docker:
      - image: python:3.8
      - image: redis:6.2
    steps:
      - checkout
      - run: python -m pip install -r test_requirements.txt
      - run: pytest tests/client/

  python-3.9-client-5:
    docker:
      - image: python:3.9
      - image: redis:5.0
    steps:
      - checkout
      - run: python -m pip install -r test_requirements.txt
      - run: pytest tests/client/

  python-3.9-client-6:
    docker:
      - image: python:3.9
      - image: redis:6.2
    steps:
      - checkout
      - run: python -m pip install -r test_requirements.txt
      - run: pytest tests/client/

  python-3.7-cluster-5:
    docker:
      - image: python:3.7
      - image: grokzen/redis-cluster:5.0.5
    steps:
      - checkout
      - run: python -m pip install -r test_requirements.txt
      - run: sleep 10  # give the cluster some init time
      - run: pytest tests/cluster/

  python-3.7-cluster-6:
    docker:
      - image: python:3.7
      - image: grokzen/redis-cluster:6.2.1
    steps:
      - checkout
      - run: python -m pip install -r test_requirements.txt
      - run: sleep 10  # give the cluster some init time
      - run: pytest tests/cluster/

  python-3.8-cluster-5:
    docker:
      - image: python:3.8
      - image: grokzen/redis-cluster:5.0.5
    steps:
      - checkout
      - run: python -m pip install -r test_requirements.txt
      - run: sleep 10  # give the cluster some init time
      - run: pytest tests/cluster/

  python-3.8-cluster-6:
    docker:
      - image: python:3.8
      - image: grokzen/redis-cluster:6.2.1
    steps:
      - checkout
      - run: python -m pip install -r test_requirements.txt
      - run: sleep 10  # give the cluster some init time
      - run: pytest tests/cluster/

  python-3.9-cluster-5:
    docker:
      - image: python:3.9
      - image: grokzen/redis-cluster:5.0.5
    steps:
      - checkout
      - run: python -m pip install -r test_requirements.txt
      - run: sleep 10  # give the cluster some init time
      - run: pytest tests/cluster/

  python-3.9-cluster-6:
    docker:
      - image: python:3.9
      - image: grokzen/redis-cluster:6.2.1
    steps:
      - checkout
      - run: python -m pip install -r test_requirements.txt
      - run: sleep 10  # give the cluster some init time
      - run: pytest tests/cluster/

  python-3.7-client-5-hiredis:
    docker:
      - image: python:3.7
      - image: redis:5.0
    steps:
      - checkout
      - run: python -m pip install -r test_requirements.txt
      - run: python -m pip install hiredis
      - run: pytest tests/client/

  python-3.7-client-6-hiredis:
    docker:
      - image: python:3.7
      - image: redis:6.2
    steps:
      - checkout
      - run: python -m pip install -r test_requirements.txt
      - run: python -m pip install hiredis
      - run: pytest tests/client/


  python-3.8-client-5-hiredis:
    docker:
      - image: python:3.8
      - image: redis:5.0
    steps:
      - checkout
      - run: python -m pip install -r test_requirements.txt
      - run: python -m pip install hiredis
      - run: pytest tests/client/

  python-3.8-client-6-hiredis:
    docker:
      - image: python:3.8
      - image: redis:6.2
    steps:
      - checkout
      - run: python -m pip install -r test_requirements.txt
      - run: python -m pip install hiredis
      - run: pytest tests/client/

  python-3.9-client-5-hiredis:
    docker:
      - image: python:3.9
      - image: redis:5.0
    steps:
      - checkout
      - run: python -m pip install -r test_requirements.txt
      - run: python -m pip install hiredis
      - run: pytest tests/client/

  python-3.9-client-6-hiredis:
    docker:
      - image: python:3.9
      - image: redis:6.2
    steps:
      - checkout
      - run: python -m pip install -r test_requirements.txt
      - run: python -m pip install hiredis
      - run: pytest tests/client/

  python-3.7-cluster-5-hiredis:
    docker:
      - image: python:3.7
      - image: grokzen/redis-cluster:5.0.5
    steps:
      - checkout
      - run: python -m pip install -r test_requirements.txt
      - run: python -m pip install hiredis
      - run: sleep 10  # give the cluster some init time
      - run: pytest tests/cluster/

  python-3.7-cluster-6-hiredis:
    docker:
      - image: python:3.7
      - image: grokzen/redis-cluster:6.2.1
    steps:
      - checkout
      - run: python -m pip install -r test_requirements.txt
      - run: python -m pip install hiredis
      - run: sleep 10  # give the cluster some init time
      - run: pytest tests/cluster/

  python-3.8-cluster-5-hiredis:
    docker:
      - image: python:3.8
      - image: grokzen/redis-cluster:5.0.5
    steps:
      - checkout
      - run: python -m pip install -r test_requirements.txt
      - run: python -m pip install hiredis
      - run: sleep 10  # give the cluster some init time
      - run: pytest tests/cluster/

  python-3.8-cluster-6-hiredis:
    docker:
      - image: python:3.8
      - image: grokzen/redis-cluster:6.2.1
    steps:
      - checkout
      - run: python -m pip install -r test_requirements.txt
      - run: python -m pip install hiredis
      - run: sleep 10  # give the cluster some init time
      - run: pytest tests/cluster/

  python-3.9-cluster-5-hiredis:
    docker:
      - image: python:3.9
      - image: grokzen/redis-cluster:5.0.5
    steps:
      - checkout
      - run: python -m pip install -r test_requirements.txt
      - run: python -m pip install hiredis
      - run: sleep 10  # give the cluster some init time
      - run: pytest tests/cluster/

  python-3.9-cluster-6-hiredis:
    docker:
      - image: python:3.9
      - image: grokzen/redis-cluster:6.2.1
    steps:
      - checkout
      - run: python -m pip install -r test_requirements.txt
      - run: python -m pip install hiredis
      - run: sleep 10  # give the cluster some init time
      - run: pytest tests/cluster/

workflows:
  version: 2
  run-jobs:
    jobs:
      - python-3.7-client-5
      - python-3.7-client-6

      - python-3.8-client-5
      - python-3.8-client-6

      - python-3.9-client-5
      - python-3.9-client-6

      - python-3.7-cluster-5
      - python-3.7-cluster-6

      - python-3.8-cluster-5
      - python-3.8-cluster-6

      - python-3.9-cluster-5
      - python-3.9-cluster-6

      - python-3.7-client-5-hiredis
      - python-3.7-client-6-hiredis

      - python-3.8-client-5-hiredis
      - python-3.8-client-6-hiredis

      - python-3.9-client-5-hiredis
      - python-3.9-client-6-hiredis

      - python-3.7-cluster-5-hiredis
      - python-3.7-cluster-6-hiredis

      - python-3.8-cluster-5-hiredis
      - python-3.8-cluster-6-hiredis

      - python-3.9-cluster-5-hiredis
      - python-3.9-cluster-6-hiredis
