version: '2.1'
orbs:
  codecov: codecov/codecov@3.1.1
jobs:
  lint:
    parameters:
      version:
        type: string
    docker:
      - image: python:<<parameters.version>>
        auth:
          username: alisaifee
          password: $DOCKERHUB_ACCESS_TOKEN
    steps:
      - checkout
      - run: pip install -r requirements/dev.txt
      - run: make lint
      - run: make generate-compatibility-docs
      - run: if [[ $(git diff --stat docs/source/compatibility.rst) != '' ]]; then echo 'Compatibility docs need updating'; exit 1; fi;
  python_37_client_5:
    docker:
      - image: python:3.7
        auth:
          username: alisaifee
          password: $DOCKERHUB_ACCESS_TOKEN
      - image: redis:5.0
        auth:
          username: alisaifee
          password: $DOCKERHUB_ACCESS_TOKEN
    steps:
      - checkout
      - run: python -m pip install -r requirements/test.txt
      - run: pytest tests/client/ --cov-report=xml
      - codecov/upload:
          file: coverage.xml

  python_37_client_6:
    docker:
      - image: python:3.7
        auth:
          username: alisaifee
          password: $DOCKERHUB_ACCESS_TOKEN
      - image: redis:6.2
        auth:
          username: alisaifee
          password: $DOCKERHUB_ACCESS_TOKEN
    steps:
      - checkout
      - run: python -m pip install -r requirements/test.txt
      - run: pytest tests/client/ --cov-report=xml
      - codecov/upload:
          file: coverage.xml

  python_38_client_5:
    docker:
      - image: python:3.8
        auth:
          username: alisaifee
          password: $DOCKERHUB_ACCESS_TOKEN
      - image: redis:5.0
        auth:
          username: alisaifee
          password: $DOCKERHUB_ACCESS_TOKEN
    steps:
      - checkout
      - run: python -m pip install -r requirements/test.txt
      - run: pytest tests/client/ --cov-report=xml
      - codecov/upload:
          file: coverage.xml

  python_38_client_6:
    docker:
      - image: python:3.8
        auth:
          username: alisaifee
          password: $DOCKERHUB_ACCESS_TOKEN
      - image: redis:6.2
        auth:
          username: alisaifee
          password: $DOCKERHUB_ACCESS_TOKEN
    steps:
      - checkout
      - run: python -m pip install -r requirements/test.txt
      - run: pytest tests/client/ --cov-report=xml
      - codecov/upload:
          file: coverage.xml

  python_39_client_5:
    docker:
      - image: python:3.9
        auth:
          username: alisaifee
          password: $DOCKERHUB_ACCESS_TOKEN
      - image: redis:5.0
        auth:
          username: alisaifee
          password: $DOCKERHUB_ACCESS_TOKEN
    steps:
      - checkout
      - run: python -m pip install -r requirements/test.txt
      - run: pytest tests/client/ --cov-report=xml
      - codecov/upload:
          file: coverage.xml

  python_39_client_6:
    docker:
      - image: python:3.9
        auth:
          username: alisaifee
          password: $DOCKERHUB_ACCESS_TOKEN
      - image: redis:6.2
        auth:
          username: alisaifee
          password: $DOCKERHUB_ACCESS_TOKEN
    steps:
      - checkout
      - run: python -m pip install -r requirements/test.txt
      - run: pytest tests/client/ --cov-report=xml
      - codecov/upload:
          file: coverage.xml

  python_310_client_5:
    docker:
      - image: python:3.10
        auth:
          username: alisaifee
          password: $DOCKERHUB_ACCESS_TOKEN
      - image: redis:5.0
        auth:
          username: alisaifee
          password: $DOCKERHUB_ACCESS_TOKEN
    steps:
      - checkout
      - run: python -m pip install -r requirements/test.txt
      - run: pytest tests/client/ --cov-report=xml
      - codecov/upload:
          file: coverage.xml

  python_310_client_6:
    docker:
      - image: python:3.10
        auth:
          username: alisaifee
          password: $DOCKERHUB_ACCESS_TOKEN
      - image: redis:6.2
        auth:
          username: alisaifee
          password: $DOCKERHUB_ACCESS_TOKEN
    steps:
      - checkout
      - run: python -m pip install -r requirements/test.txt
      - run: pytest tests/client/ --cov-report=xml
      - codecov/upload:
          file: coverage.xml

  python_37_cluster_5:
    docker:
      - image: python:3.7
        auth:
          username: alisaifee
          password: $DOCKERHUB_ACCESS_TOKEN
      - image: grokzen/redis-cluster:5.0.5
        auth:
          username: alisaifee
          password: $DOCKERHUB_ACCESS_TOKEN
    steps:
      - checkout
      - run: python -m pip install -r requirements/test.txt
      - run: sleep 10  # give the cluster some init time
      - run: pytest tests/cluster/ --cov-report=xml
      - codecov/upload:
          file: coverage.xml

  python_37_cluster_6:
    docker:
      - image: python:3.7
        auth:
          username: alisaifee
          password: $DOCKERHUB_ACCESS_TOKEN
      - image: grokzen/redis-cluster:6.2.1
        auth:
          username: alisaifee
          password: $DOCKERHUB_ACCESS_TOKEN
    steps:
      - checkout
      - run: python -m pip install -r requirements/test.txt
      - run: sleep 10  # give the cluster some init time
      - run: pytest tests/cluster/ --cov-report=xml
      - codecov/upload:
          file: coverage.xml

  python_38_cluster_5:
    docker:
      - image: python:3.8
        auth:
          username: alisaifee
          password: $DOCKERHUB_ACCESS_TOKEN
      - image: grokzen/redis-cluster:5.0.5
        auth:
          username: alisaifee
          password: $DOCKERHUB_ACCESS_TOKEN
    steps:
      - checkout
      - run: python -m pip install -r requirements/test.txt
      - run: sleep 10  # give the cluster some init time
      - run: pytest tests/cluster/ --cov-report=xml
      - codecov/upload:
          file: coverage.xml

  python_38_cluster_6:
    docker:
      - image: python:3.8
        auth:
          username: alisaifee
          password: $DOCKERHUB_ACCESS_TOKEN
      - image: grokzen/redis-cluster:6.2.1
        auth:
          username: alisaifee
          password: $DOCKERHUB_ACCESS_TOKEN
    steps:
      - checkout
      - run: python -m pip install -r requirements/test.txt
      - run: sleep 10  # give the cluster some init time
      - run: pytest tests/cluster/ --cov-report=xml
      - codecov/upload:
          file: coverage.xml

  python_39_cluster_5:
    docker:
      - image: python:3.9
        auth:
          username: alisaifee
          password: $DOCKERHUB_ACCESS_TOKEN
      - image: grokzen/redis-cluster:5.0.5
        auth:
          username: alisaifee
          password: $DOCKERHUB_ACCESS_TOKEN
    steps:
      - checkout
      - run: python -m pip install -r requirements/test.txt
      - run: sleep 10  # give the cluster some init time
      - run: pytest tests/cluster/ --cov-report=xml
      - codecov/upload:
          file: coverage.xml

  python_39_cluster_6:
    docker:
      - image: python:3.9
        auth:
          username: alisaifee
          password: $DOCKERHUB_ACCESS_TOKEN
      - image: grokzen/redis-cluster:6.2.1
        auth:
          username: alisaifee
          password: $DOCKERHUB_ACCESS_TOKEN
    steps:
      - checkout
      - run: python -m pip install -r requirements/test.txt
      - run: sleep 10  # give the cluster some init time
      - run: pytest tests/cluster/ --cov-report=xml
      - codecov/upload:
          file: coverage.xml

  python_310_cluster_5:
    docker:
      - image: python:3.10
        auth:
          username: alisaifee
          password: $DOCKERHUB_ACCESS_TOKEN
      - image: grokzen/redis-cluster:5.0.5
        auth:
          username: alisaifee
          password: $DOCKERHUB_ACCESS_TOKEN
    steps:
      - checkout
      - run: python -m pip install -r requirements/test.txt
      - run: sleep 10  # give the cluster some init time
      - run: pytest tests/cluster/ --cov-report=xml
      - codecov/upload:
          file: coverage.xml

  python_310_cluster_6:
    docker:
      - image: python:3.10
        auth:
          username: alisaifee
          password: $DOCKERHUB_ACCESS_TOKEN
      - image: grokzen/redis-cluster:6.2.1
        auth:
          username: alisaifee
          password: $DOCKERHUB_ACCESS_TOKEN
    steps:
      - checkout
      - run: python -m pip install -r requirements/test.txt
      - run: sleep 10  # give the cluster some init time
      - run: pytest tests/cluster/ --cov-report=xml
      - codecov/upload:
          file: coverage.xml

  python_37_client_5_hiredis:
    docker:
      - image: python:3.7
        auth:
          username: alisaifee
          password: $DOCKERHUB_ACCESS_TOKEN
      - image: redis:5.0
        auth:
          username: alisaifee
          password: $DOCKERHUB_ACCESS_TOKEN
    steps:
      - checkout
      - run: python -m pip install -r requirements/test.txt
      - run: python -m pip install hiredis
      - run: pytest tests/client/ --cov-report=xml
      - codecov/upload:
          file: coverage.xml

  python_37_client_6_hiredis:
    docker:
      - image: python:3.7
        auth:
          username: alisaifee
          password: $DOCKERHUB_ACCESS_TOKEN
      - image: redis:6.2
        auth:
          username: alisaifee
          password: $DOCKERHUB_ACCESS_TOKEN
    steps:
      - checkout
      - run: python -m pip install -r requirements/test.txt
      - run: python -m pip install hiredis
      - run: pytest tests/client/ --cov-report=xml
      - codecov/upload:
          file: coverage.xml


  python_38_client_5_hiredis:
    docker:
      - image: python:3.8
        auth:
          username: alisaifee
          password: $DOCKERHUB_ACCESS_TOKEN
      - image: redis:5.0
        auth:
          username: alisaifee
          password: $DOCKERHUB_ACCESS_TOKEN
    steps:
      - checkout
      - run: python -m pip install -r requirements/test.txt
      - run: python -m pip install hiredis
      - run: pytest tests/client/ --cov-report=xml
      - codecov/upload:
          file: coverage.xml

  python_38_client_6_hiredis:
    docker:
      - image: python:3.8
        auth:
          username: alisaifee
          password: $DOCKERHUB_ACCESS_TOKEN
      - image: redis:6.2
        auth:
          username: alisaifee
          password: $DOCKERHUB_ACCESS_TOKEN
    steps:
      - checkout
      - run: python -m pip install -r requirements/test.txt
      - run: python -m pip install hiredis
      - run: pytest tests/client/ --cov-report=xml
      - codecov/upload:
          file: coverage.xml

  python_39_client_5_hiredis:
    docker:
      - image: python:3.9
        auth:
          username: alisaifee
          password: $DOCKERHUB_ACCESS_TOKEN
      - image: redis:5.0
        auth:
          username: alisaifee
          password: $DOCKERHUB_ACCESS_TOKEN
    steps:
      - checkout
      - run: python -m pip install -r requirements/test.txt
      - run: python -m pip install hiredis
      - run: pytest tests/client/ --cov-report=xml
      - codecov/upload:
          file: coverage.xml

  python_39_client_6_hiredis:
    docker:
      - image: python:3.9
        auth:
          username: alisaifee
          password: $DOCKERHUB_ACCESS_TOKEN
      - image: redis:6.2
        auth:
          username: alisaifee
          password: $DOCKERHUB_ACCESS_TOKEN
    steps:
      - checkout
      - run: python -m pip install -r requirements/test.txt
      - run: python -m pip install hiredis
      - run: pytest tests/client/ --cov-report=xml
      - codecov/upload:
          file: coverage.xml

  python_310_client_5_hiredis:
    docker:
      - image: python:3.10
        auth:
          username: alisaifee
          password: $DOCKERHUB_ACCESS_TOKEN
      - image: redis:5.0
        auth:
          username: alisaifee
          password: $DOCKERHUB_ACCESS_TOKEN
    steps:
      - checkout
      - run: python -m pip install -r requirements/test.txt
      - run: python -m pip install hiredis
      - run: pytest tests/client/ --cov-report=xml
      - codecov/upload:
          file: coverage.xml

  python_310_client_6_hiredis:
    docker:
      - image: python:3.10
        auth:
          username: alisaifee
          password: $DOCKERHUB_ACCESS_TOKEN
      - image: redis:6.2
        auth:
          username: alisaifee
          password: $DOCKERHUB_ACCESS_TOKEN
    steps:
      - checkout
      - run: python -m pip install -r requirements/test.txt
      - run: python -m pip install hiredis
      - run: pytest tests/client/ --cov-report=xml
      - codecov/upload:
          file: coverage.xml

  python_37_cluster_5_hiredis:
    docker:
      - image: python:3.7
        auth:
          username: alisaifee
          password: $DOCKERHUB_ACCESS_TOKEN
      - image: grokzen/redis-cluster:5.0.5
        auth:
          username: alisaifee
          password: $DOCKERHUB_ACCESS_TOKEN
    steps:
      - checkout
      - run: python -m pip install -r requirements/test.txt
      - run: python -m pip install hiredis
      - run: sleep 10  # give the cluster some init time
      - run: pytest tests/cluster/ --cov-report=xml
      - codecov/upload:
          file: coverage.xml

  python_37_cluster_6_hiredis:
    docker:
      - image: python:3.7
        auth:
          username: alisaifee
          password: $DOCKERHUB_ACCESS_TOKEN
      - image: grokzen/redis-cluster:6.2.1
        auth:
          username: alisaifee
          password: $DOCKERHUB_ACCESS_TOKEN
    steps:
      - checkout
      - run: python -m pip install -r requirements/test.txt
      - run: python -m pip install hiredis
      - run: sleep 10  # give the cluster some init time
      - run: pytest tests/cluster/ --cov-report=xml
      - codecov/upload:
          file: coverage.xml

  python_38_cluster_5_hiredis:
    docker:
      - image: python:3.8
        auth:
          username: alisaifee
          password: $DOCKERHUB_ACCESS_TOKEN
      - image: grokzen/redis-cluster:5.0.5
        auth:
          username: alisaifee
          password: $DOCKERHUB_ACCESS_TOKEN
    steps:
      - checkout
      - run: python -m pip install -r requirements/test.txt
      - run: python -m pip install hiredis
      - run: sleep 10  # give the cluster some init time
      - run: pytest tests/cluster/ --cov-report=xml
      - codecov/upload:
          file: coverage.xml

  python_38_cluster_6_hiredis:
    docker:
      - image: python:3.8
        auth:
          username: alisaifee
          password: $DOCKERHUB_ACCESS_TOKEN
      - image: grokzen/redis-cluster:6.2.1
        auth:
          username: alisaifee
          password: $DOCKERHUB_ACCESS_TOKEN
    steps:
      - checkout
      - run: python -m pip install -r requirements/test.txt
      - run: python -m pip install hiredis
      - run: sleep 10  # give the cluster some init time
      - run: pytest tests/cluster/ --cov-report=xml
      - codecov/upload:
          file: coverage.xml

  python_39_cluster_5_hiredis:
    docker:
      - image: python:3.9
        auth:
          username: alisaifee
          password: $DOCKERHUB_ACCESS_TOKEN
      - image: grokzen/redis-cluster:5.0.5
        auth:
          username: alisaifee
          password: $DOCKERHUB_ACCESS_TOKEN
    steps:
      - checkout
      - run: python -m pip install -r requirements/test.txt
      - run: python -m pip install hiredis
      - run: sleep 10  # give the cluster some init time
      - run: pytest tests/cluster/ --cov-report=xml
      - codecov/upload:
          file: coverage.xml

  python_39_cluster_6_hiredis:
    docker:
      - image: python:3.9
        auth:
          username: alisaifee
          password: $DOCKERHUB_ACCESS_TOKEN
      - image: grokzen/redis-cluster:6.2.1
        auth:
          username: alisaifee
          password: $DOCKERHUB_ACCESS_TOKEN
    steps:
      - checkout
      - run: python -m pip install -r requirements/test.txt
      - run: python -m pip install hiredis
      - run: sleep 10  # give the cluster some init time
      - run: pytest tests/cluster/ --cov-report=xml
      - codecov/upload:
          file: coverage.xml

  python_310_cluster_5_hiredis:
    docker:
      - image: python:3.10
        auth:
          username: alisaifee
          password: $DOCKERHUB_ACCESS_TOKEN
      - image: grokzen/redis-cluster:5.0.5
        auth:
          username: alisaifee
          password: $DOCKERHUB_ACCESS_TOKEN
    steps:
      - checkout
      - run: python -m pip install -r requirements/test.txt
      - run: python -m pip install hiredis
      - run: sleep 10  # give the cluster some init time
      - run: pytest tests/cluster/ --cov-report=xml
      - codecov/upload:
          file: coverage.xml

  python_310_cluster_6_hiredis:
    docker:
      - image: python:3.10
        auth:
          username: alisaifee
          password: $DOCKERHUB_ACCESS_TOKEN
      - image: grokzen/redis-cluster:6.2.1
        auth:
          username: alisaifee
          password: $DOCKERHUB_ACCESS_TOKEN
    steps:
      - checkout
      - run: python -m pip install -r requirements/test.txt
      - run: python -m pip install hiredis
      - run: sleep 10  # give the cluster some init time
      - run: pytest tests/cluster/ --cov-report=xml
      - codecov/upload:
          file: coverage.xml

workflows:
  version: 2
  run-jobs:
    jobs:
      - lint:
          matrix:
            parameters:
              version: ["3.7", "3.8", "3.9", "3.10"]
      - python_37_client_5
      - python_37_client_6

      - python_38_client_5
      - python_38_client_6

      - python_39_client_5
      - python_39_client_6

      - python_310_client_5
      - python_310_client_6


      - python_37_cluster_5
      - python_37_cluster_6

      - python_38_cluster_5
      - python_38_cluster_6

      - python_39_cluster_5
      - python_39_cluster_6

      - python_310_cluster_5
      - python_310_cluster_6

      - python_37_client_5_hiredis
      - python_37_client_6_hiredis

      - python_38_client_5_hiredis
      - python_38_client_6_hiredis

      - python_39_client_5_hiredis
      - python_39_client_6_hiredis

      - python_310_client_5_hiredis
      - python_310_client_6_hiredis

      - python_37_cluster_5_hiredis
      - python_37_cluster_6_hiredis

      - python_38_cluster_5_hiredis
      - python_38_cluster_6_hiredis

      - python_39_cluster_5_hiredis
      - python_39_cluster_6_hiredis

      - python_310_cluster_5_hiredis
      - python_310_cluster_6_hiredis

