version: '2.1'
orbs:
  codecov: codecov/codecov@3.1.1
jobs:
  lint:
    parameters:
      version:
        type: string
    docker:
      - image: python:<<parameters.version>>
        auth:
          username: alisaifee
          password: $DOCKERHUB_ACCESS_TOKEN
    steps:
      - checkout
      - run: pip install -r requirements/dev.txt
      - run: make lint
  check-docs:
    docker:
      - image: python:3.10
        auth:
          username: alisaifee
          password: $DOCKERHUB_ACCESS_TOKEN
    steps:
      - checkout
      - run: pip install -r requirements/dev.txt
      - run: make generate-compatibility-docs
      - run: if [[ $(git diff --stat docs/source/compatibility.rst) != '' ]]; then echo 'Compatibility docs need updating'; exit 1; fi;
  standard:
    parameters:
      python-version:
        type: string
      redis-version:
        type: string
    docker:
      - image: python:<<parameters.python-version>>
        auth:
          username: alisaifee
          password: $DOCKERHUB_ACCESS_TOKEN
      - image: redis:<<parameters.redis-version>>
        auth:
          username: alisaifee
          password: $DOCKERHUB_ACCESS_TOKEN
    steps:
      - checkout
      - run: python -m pip install -r requirements/test.txt
      - run: pytest tests/client/ --cov-report=xml
      - codecov/upload:
          file: coverage.xml
  cluster:
    parameters:
      python-version:
        type: string
      cluster-version:
        type: string
    docker:
      - image: python:<<parameters.python-version>>
        auth:
          username: alisaifee
          password: $DOCKERHUB_ACCESS_TOKEN
      - image: grokzen/redis-cluster:<<parameters.cluster-version>>
        auth:
          username: alisaifee
          password: $DOCKERHUB_ACCESS_TOKEN
    steps:
      - checkout
      - run: python -m pip install -r requirements/test.txt
      - run: sleep 10  # give the cluster some init time
      - run: pytest tests/cluster/ --cov-report=xml
      - codecov/upload:
          file: coverage.xml

workflows:
  version: 2
  run-jobs:
    jobs:
      - lint:
          matrix:
            parameters:
              version: ["3.7", "3.8", "3.9", "3.10"]
      - check-docs
      - standard:
          matrix:
            parameters:
              python-version: ["3.7", "3.8", "3.9", "3.10"]
              redis-version: ["5.0", "6.2"]
      - cluster:
          matrix:
            parameters:
              python-version: ["3.7", "3.8", "3.9", "3.10"]
              cluster-version: ["5.0.5", "6.2.1"]
