name: CI

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python_version: [3.8, 3.9, "3.10", "3.11"]
        service_version:
          - REDIS_VERSION=5.0.14 REDIS_SENTINEL_VERSION=5.0.14 REDIS_SSL_VERSION=6.2.6
          - REDIS_VERSION=6.0.16 REDIS_SENTINEL_VERSION=6.0.16 REDIS_SSL_VERSION=6.0.16
          - REDIS_VERSION=6.2.6 REDIS_SSL_VERSION=6.2.6 REDIS_SENTINEL_VERSION=6.2.6 REDIS_STACK_VERSION=6.2.0-edge
          - REDIS_VERSION=7.0-rc2 REDIS_SSL_VERSION=7.0-rc2 REDIS_STACK_VERSION=7.0.0-edge
        parser: [hiredis, python]
        uvloop: ["False"]
        include:
          - python-version: 3.9
            service_version: "REDIS_VERSION=latest REDIS_SSL_VERSION=latest"
            parser: hiredis
            uvloop: "True"
          - python-version: "3.10"
            service_version: "REDIS_VERSION=latest REDIS_SSL_VERSION=latest"
            parser: hiredis
            uvloop: "True"
    steps:
    - uses: actions/checkout@v3
    - name: Cache dependencies
      uses: actions/cache@v1
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-${{ matrix.python-version }}-pip-${{ hashFiles('requirements/**') }}
        restore-keys: |
          ${{ runner.os }}-${{ matrix.python-version }}-pip-
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip setuptools wheel
        pip install -r requirements/dev.txt
        pip uninstall hiredis -y
        python setup.py build_stubs
    - name: Install Hiredis
      if: ${{ matrix.parser == 'hiredis' }}
      run:
        pip install hiredis
    - name: Tests
      env:
        COREDIS_UVLOOP: "{{matrix.uvloop}}"
        HOST_OS: linux
        CI: "True"
      run: |
        eval "export ${{ matrix.service_version }}"
        pytest --cov-report=xml --cov-branch
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v2
